kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3.6.3-openjdk-11
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - mvn clean install -DskipTests
  - docker build . -t spring-app-image
  - docker tag spring-app-image dindocker13/spring-app-image:new
  - docker push dindocker13/spring-app-image:new
